CREATE MIGRATION m14ykski3w4jenuq7brch5v5bhght5ybtp2gqr2mmhynledbo3j6gq
    ONTO m1ryrngpym75cc5zcmkrfebkg6dcmyflzu7727vnjhmy2zl4q3tjda
{
  CREATE EXTENSION pgvector VERSION '0.4';
  CREATE MODULE codegen IF NOT EXISTS;
  CREATE ABSTRACT TYPE codegen::A {
      CREATE MULTI LINK ml_a: codegen::A;
      CREATE LINK ol_a: codegen::A;
      CREATE REQUIRED PROPERTY rp_a_str: std::str;
  };
  CREATE ABSTRACT TYPE codegen::B {
      CREATE REQUIRED PROPERTY rp_b_str: std::str;
  };
  CREATE ABSTRACT TYPE codegen::C EXTENDING codegen::B {
      CREATE REQUIRED PROPERTY rp_c_str: std::str;
  };
  CREATE ABSTRACT TYPE codegen::D EXTENDING codegen::A, codegen::C {
      CREATE REQUIRED PROPERTY rp_d_str: std::str;
  };
  CREATE TYPE codegen::E EXTENDING codegen::A {
      CREATE REQUIRED PROPERTY rp_e_str: std::str;
  };
  CREATE TYPE codegen::F EXTENDING codegen::D {
      CREATE MULTI LINK ml_a_b: (codegen::B | codegen::A);
      CREATE LINK ol_a_b: (codegen::B | codegen::A);
      ALTER LINK ml_a {
          SET MULTI;
          SET OWNED;
          SET TYPE codegen::E USING (<codegen::E>{});
      };
      ALTER LINK ol_a {
          SET OWNED;
          SET TYPE codegen::E USING (<codegen::E>{});
      };
      ALTER PROPERTY rp_a_str {
          SET OWNED;
          SET TYPE std::str;
      };
      CREATE REQUIRED PROPERTY rp_f_str: std::str;
  };
  CREATE SCALAR TYPE codegen::BoolType EXTENDING std::bool;
  CREATE SCALAR TYPE codegen::BytesType EXTENDING std::bytes;
  CREATE SCALAR TYPE codegen::CalDateDurationType EXTENDING cal::date_duration;
  CREATE SCALAR TYPE codegen::CalLocalDateType EXTENDING cal::local_date;
  CREATE SCALAR TYPE codegen::CalLocalDatetimeType EXTENDING cal::local_datetime;
  CREATE SCALAR TYPE codegen::CalLocalTimeType EXTENDING cal::local_time;
  CREATE SCALAR TYPE codegen::CalRelativeDurationType EXTENDING cal::relative_duration;
  CREATE SCALAR TYPE codegen::CfgMemoryType EXTENDING cfg::memory;
  CREATE SCALAR TYPE codegen::DatetimeType EXTENDING std::datetime;
  CREATE SCALAR TYPE codegen::DecimalType EXTENDING std::decimal;
  CREATE SCALAR TYPE codegen::DurationType EXTENDING std::duration;
  CREATE SCALAR TYPE codegen::EnumType EXTENDING enum<A, B, C>;
  CREATE SCALAR TYPE codegen::Float32Type EXTENDING std::float32;
  CREATE SCALAR TYPE codegen::Float64Type EXTENDING std::float64;
  CREATE SCALAR TYPE codegen::Int16Type EXTENDING std::int16;
  CREATE SCALAR TYPE codegen::Int32Type EXTENDING std::int32;
  CREATE SCALAR TYPE codegen::Int64Type EXTENDING std::int64;
  CREATE SCALAR TYPE codegen::JsonType EXTENDING std::json;
  CREATE SCALAR TYPE codegen::SequenceType EXTENDING std::sequence;
  CREATE SCALAR TYPE codegen::StrType EXTENDING std::str;
  CREATE SCALAR TYPE codegen::UuidType EXTENDING std::uuid;
  CREATE SCALAR TYPE codegen::VectorType EXTENDING ext::pgvector::vector<1>;
  CREATE TYPE codegen::Result {
      CREATE MULTI PROPERTY mp_array_int64: array<std::int64>;
      CREATE PROPERTY op_array_int64: array<std::int64>;
      CREATE REQUIRED PROPERTY rp_array_int64: array<std::int64>;
      CREATE MULTI LINK ml_f: codegen::F;
      CREATE LINK ol_f: codegen::F;
      CREATE REQUIRED LINK rl_f: codegen::F;
      CREATE REQUIRED LINK rl_lp_f: codegen::F {
          CREATE PROPERTY olp_a: std::int64;
      };
      CREATE MULTI PROPERTY mp_bool: std::bool;
      CREATE MULTI PROPERTY mp_bool_type: codegen::BoolType;
      CREATE MULTI PROPERTY mp_bytes: std::bytes;
      CREATE MULTI PROPERTY mp_bytes_type: codegen::BytesType;
      CREATE MULTI PROPERTY mp_cal_date_duration: cal::date_duration;
      CREATE MULTI PROPERTY mp_cal_date_duration_type: codegen::CalDateDurationType;
      CREATE MULTI PROPERTY mp_cal_local_date: cal::local_date;
      CREATE MULTI PROPERTY mp_cal_local_date_type: codegen::CalLocalDateType;
      CREATE MULTI PROPERTY mp_cal_local_datetime: cal::local_datetime;
      CREATE MULTI PROPERTY mp_cal_local_datetime_type: codegen::CalLocalDatetimeType;
      CREATE MULTI PROPERTY mp_cal_local_time: cal::local_time;
      CREATE MULTI PROPERTY mp_cal_local_time_type: codegen::CalLocalTimeType;
      CREATE MULTI PROPERTY mp_cal_relative_duration: cal::relative_duration;
      CREATE MULTI PROPERTY mp_cal_relative_duration_type: codegen::CalRelativeDurationType;
      CREATE MULTI PROPERTY mp_cfg_memory: cfg::memory;
      CREATE MULTI PROPERTY mp_cfg_memory_type: codegen::CfgMemoryType;
      CREATE MULTI PROPERTY mp_datetime: std::datetime;
      CREATE MULTI PROPERTY mp_datetime_type: codegen::DatetimeType;
      CREATE MULTI PROPERTY mp_decimal: std::decimal;
      CREATE MULTI PROPERTY mp_decimal_type: codegen::DecimalType;
      CREATE MULTI PROPERTY mp_duration: std::duration;
      CREATE MULTI PROPERTY mp_duration_type: codegen::DurationType;
      CREATE MULTI PROPERTY mp_enum: codegen::EnumType;
      CREATE MULTI PROPERTY mp_float32: std::float32;
      CREATE MULTI PROPERTY mp_float32_type: codegen::Float32Type;
      CREATE MULTI PROPERTY mp_float64: std::float64;
      CREATE MULTI PROPERTY mp_float64_type: codegen::Float64Type;
      CREATE MULTI PROPERTY mp_int16: std::int16;
      CREATE MULTI PROPERTY mp_int16_type: codegen::Int16Type;
      CREATE MULTI PROPERTY mp_int32: std::int32;
      CREATE MULTI PROPERTY mp_int32_type: codegen::Int32Type;
      CREATE MULTI PROPERTY mp_int64: std::int64;
      CREATE MULTI PROPERTY mp_int64_type: codegen::Int64Type;
      CREATE MULTI PROPERTY mp_json: std::json;
      CREATE MULTI PROPERTY mp_json_type: codegen::JsonType;
      CREATE MULTI PROPERTY mp_named_tuple_x_int64_y_int64: tuple<x: std::int64, y: std::int64>;
      CREATE MULTI PROPERTY mp_range_cal_local_date: range<cal::local_date>;
      CREATE MULTI PROPERTY mp_range_cal_local_datetime: range<cal::local_datetime>;
      CREATE MULTI PROPERTY mp_range_datetime: range<std::datetime>;
      CREATE MULTI PROPERTY mp_range_decimal: range<std::decimal>;
      CREATE MULTI PROPERTY mp_range_float32: range<std::float32>;
      CREATE MULTI PROPERTY mp_range_float64: range<std::float64>;
      CREATE MULTI PROPERTY mp_range_int32: range<std::int32>;
      CREATE MULTI PROPERTY mp_range_int64: range<std::int64>;
      CREATE MULTI PROPERTY mp_sequence: codegen::SequenceType;
      CREATE MULTI PROPERTY mp_str: std::str;
      CREATE MULTI PROPERTY mp_str_type: codegen::StrType;
      CREATE MULTI PROPERTY mp_tuple_int64_int64: tuple<std::int64, std::int64>;
      CREATE MULTI PROPERTY mp_uuid: std::uuid;
      CREATE MULTI PROPERTY mp_uuid_type: codegen::UuidType;
      CREATE MULTI PROPERTY mp_vector_type: codegen::VectorType;
      CREATE PROPERTY op_bool: std::bool;
      CREATE PROPERTY op_bool_type: codegen::BoolType;
      CREATE PROPERTY op_bytes: std::bytes;
      CREATE PROPERTY op_bytes_type: codegen::BytesType;
      CREATE PROPERTY op_cal_date_duration: cal::date_duration;
      CREATE PROPERTY op_cal_date_duration_type: codegen::CalDateDurationType;
      CREATE PROPERTY op_cal_local_date: cal::local_date;
      CREATE PROPERTY op_cal_local_date_type: codegen::CalLocalDateType;
      CREATE PROPERTY op_cal_local_datetime: cal::local_datetime;
      CREATE PROPERTY op_cal_local_datetime_type: codegen::CalLocalDatetimeType;
      CREATE PROPERTY op_cal_local_time: cal::local_time;
      CREATE PROPERTY op_cal_local_time_type: codegen::CalLocalTimeType;
      CREATE PROPERTY op_cal_relative_duration: cal::relative_duration;
      CREATE PROPERTY op_cal_relative_duration_type: codegen::CalRelativeDurationType;
      CREATE PROPERTY op_cfg_memory: cfg::memory;
      CREATE PROPERTY op_cfg_memory_type: codegen::CfgMemoryType;
      CREATE PROPERTY op_datetime: std::datetime;
      CREATE PROPERTY op_datetime_type: codegen::DatetimeType;
      CREATE PROPERTY op_decimal: std::decimal;
      CREATE PROPERTY op_decimal_type: codegen::DecimalType;
      CREATE PROPERTY op_duration: std::duration;
      CREATE PROPERTY op_duration_type: codegen::DurationType;
      CREATE PROPERTY op_enum: codegen::EnumType;
      CREATE PROPERTY op_float32: std::float32;
      CREATE PROPERTY op_float32_type: codegen::Float32Type;
      CREATE PROPERTY op_float64: std::float64;
      CREATE PROPERTY op_float64_type: codegen::Float64Type;
      CREATE PROPERTY op_int16: std::int16;
      CREATE PROPERTY op_int16_type: codegen::Int16Type;
      CREATE PROPERTY op_int32: std::int32;
      CREATE PROPERTY op_int32_type: codegen::Int32Type;
      CREATE PROPERTY op_int64: std::int64;
      CREATE PROPERTY op_int64_type: codegen::Int64Type;
      CREATE PROPERTY op_json: std::json;
      CREATE PROPERTY op_json_type: codegen::JsonType;
      CREATE PROPERTY op_named_tuple_x_int64_y_int64: tuple<x: std::int64, y: std::int64>;
      CREATE PROPERTY op_range_cal_local_date: range<cal::local_date>;
      CREATE PROPERTY op_range_cal_local_datetime: range<cal::local_datetime>;
      CREATE PROPERTY op_range_datetime: range<std::datetime>;
      CREATE PROPERTY op_range_decimal: range<std::decimal>;
      CREATE PROPERTY op_range_float32: range<std::float32>;
      CREATE PROPERTY op_range_float64: range<std::float64>;
      CREATE PROPERTY op_range_int32: range<std::int32>;
      CREATE PROPERTY op_range_int64: range<std::int64>;
      CREATE PROPERTY op_sequence: codegen::SequenceType;
      CREATE PROPERTY op_str: std::str;
      CREATE PROPERTY op_str_type: codegen::StrType;
      CREATE PROPERTY op_tuple_int64_int64: tuple<std::int64, std::int64>;
      CREATE PROPERTY op_uuid: std::uuid;
      CREATE PROPERTY op_uuid_type: codegen::UuidType;
      CREATE PROPERTY op_vector_type: codegen::VectorType;
      CREATE REQUIRED PROPERTY rp_bool: std::bool;
      CREATE REQUIRED PROPERTY rp_bool_type: codegen::BoolType;
      CREATE REQUIRED PROPERTY rp_bytes: std::bytes;
      CREATE REQUIRED PROPERTY rp_bytes_type: codegen::BytesType;
      CREATE REQUIRED PROPERTY rp_cal_date_duration: cal::date_duration;
      CREATE REQUIRED PROPERTY rp_cal_date_duration_type: codegen::CalDateDurationType;
      CREATE REQUIRED PROPERTY rp_cal_local_date: cal::local_date;
      CREATE REQUIRED PROPERTY rp_cal_local_date_type: codegen::CalLocalDateType;
      CREATE REQUIRED PROPERTY rp_cal_local_datetime: cal::local_datetime;
      CREATE REQUIRED PROPERTY rp_cal_local_datetime_type: codegen::CalLocalDatetimeType;
      CREATE REQUIRED PROPERTY rp_cal_local_time: cal::local_time;
      CREATE REQUIRED PROPERTY rp_cal_local_time_type: codegen::CalLocalTimeType;
      CREATE REQUIRED PROPERTY rp_cal_relative_duration: cal::relative_duration;
      CREATE REQUIRED PROPERTY rp_cal_relative_duration_type: codegen::CalRelativeDurationType;
      CREATE REQUIRED PROPERTY rp_cfg_memory: cfg::memory;
      CREATE REQUIRED PROPERTY rp_cfg_memory_type: codegen::CfgMemoryType;
      CREATE REQUIRED PROPERTY rp_datetime: std::datetime;
      CREATE REQUIRED PROPERTY rp_datetime_type: codegen::DatetimeType;
      CREATE REQUIRED PROPERTY rp_decimal: std::decimal;
      CREATE REQUIRED PROPERTY rp_decimal_type: codegen::DecimalType;
      CREATE REQUIRED PROPERTY rp_duration: std::duration;
      CREATE REQUIRED PROPERTY rp_duration_type: codegen::DurationType;
      CREATE REQUIRED PROPERTY rp_enum: codegen::EnumType;
      CREATE REQUIRED PROPERTY rp_float32: std::float32;
      CREATE REQUIRED PROPERTY rp_float32_type: codegen::Float32Type;
      CREATE REQUIRED PROPERTY rp_float64: std::float64;
      CREATE REQUIRED PROPERTY rp_float64_type: codegen::Float64Type;
      CREATE REQUIRED PROPERTY rp_int16: std::int16;
      CREATE REQUIRED PROPERTY rp_int16_type: codegen::Int16Type;
      CREATE REQUIRED PROPERTY rp_int32: std::int32;
      CREATE REQUIRED PROPERTY rp_int32_type: codegen::Int32Type;
      CREATE REQUIRED PROPERTY rp_int64: std::int64;
      CREATE REQUIRED PROPERTY rp_int64_type: codegen::Int64Type;
      CREATE REQUIRED PROPERTY rp_json: std::json;
      CREATE REQUIRED PROPERTY rp_json_type: codegen::JsonType;
      CREATE REQUIRED PROPERTY rp_named_tuple_x_int64_y_int64: tuple<x: std::int64, y: std::int64>;
      CREATE REQUIRED PROPERTY rp_range_cal_local_date: range<cal::local_date>;
      CREATE REQUIRED PROPERTY rp_range_cal_local_datetime: range<cal::local_datetime>;
      CREATE REQUIRED PROPERTY rp_range_datetime: range<std::datetime>;
      CREATE REQUIRED PROPERTY rp_range_decimal: range<std::decimal>;
      CREATE REQUIRED PROPERTY rp_range_float32: range<std::float32>;
      CREATE REQUIRED PROPERTY rp_range_float64: range<std::float64>;
      CREATE REQUIRED PROPERTY rp_range_int32: range<std::int32>;
      CREATE REQUIRED PROPERTY rp_range_int64: range<std::int64>;
      CREATE REQUIRED PROPERTY rp_sequence: codegen::SequenceType;
      CREATE REQUIRED PROPERTY rp_str: std::str;
      CREATE REQUIRED PROPERTY rp_str_type: codegen::StrType;
      CREATE REQUIRED PROPERTY rp_tuple_int64_int64: tuple<std::int64, std::int64>;
      CREATE REQUIRED PROPERTY rp_uuid: std::uuid;
      CREATE REQUIRED PROPERTY rp_uuid_type: codegen::UuidType;
      CREATE REQUIRED PROPERTY rp_vector_type: codegen::VectorType;
  };
  CREATE SCALAR TYPE default::ExVector EXTENDING ext::pgvector::vector<1602>;
};
