# AUTOGENERATED: DO NOT MODIFY
# Generated by Elixir client for EdgeDB via `mix edgedb.generate` from
#   `priv/edgedb/edgeql/select_string_from_root.edgeql`.
defmodule Tests.Codegen.Queries.SelectStringFromRoot do
  @query """
  select 'Hello world!'
  """

  @moduledoc """
  Generated module for the EdgeQL query from
    `priv/edgedb/edgeql/select_string_from_root.edgeql`.

  Query:

  ```edgeql
  #{@query}
  ```
  """

  @doc """
  Run the query.
  """
  @spec query(
          client :: EdgeDB.client(),
          opts :: list(EdgeDB.query_option())
        ) ::
          {:ok, String.t()}
          | {:error, reason}
        when reason: any()
  def query(client, opts \\ []) do
    do_query(client, [], opts)
  end

  @doc """
  Run the query.
  """
  @spec query!(
          client :: EdgeDB.client(),
          opts :: list(EdgeDB.query_option())
        ) :: String.t()
  def query!(client, opts \\ []) do
    case do_query(client, [], opts) do
      {:ok, result} ->
        result

      {:error, exc} ->
        raise exc
    end
  end

  defp do_query(client, args, opts) do
    with {:ok, result} <- EdgeDB.query_required_single(client, @query, args, opts) do
      {:ok, result}
    end
  end
end
