name: Release package in Hex

on:
  release:
    types:
      - "published"

env:
  MIX_ENV: ci

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0"
          elixir-version: "1.15"

      - name: Install dependencies
        run: mix deps.get

      - name: Publish to Hex
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: mix hex.publish --yes
